const College = require('../models/College.model');
const User = require('../models/User.model');
const logger = require('../config/logger');
const slugify = require('slugify');

const colleges = [
  { name: 'Indian Institute of Technology Bombay', type: 'public', description: 'Premier engineering institute known for cutting-edge research, innovation, and producing top-tier engineers and entrepreneurs.', location: { address: 'IIT Bombay, Powai', city: 'Mumbai', state: 'Maharashtra', pincode: '400076' }, fees: { min: 200000, max: 1000000, currency: 'INR' }, ranking: 1, established: 1958, website: 'https://www.iitb.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Hospital', 'Cafeteria', 'Gymnasium', 'Swimming Pool', 'Auditorium'] },
  { name: 'Indian Institute of Technology Delhi', type: 'public', description: 'One of India\'s most prestigious engineering institutions with world-class faculty and research facilities.', location: { address: 'Hauz Khas', city: 'New Delhi', state: 'Delhi', pincode: '110016' }, fees: { min: 200000, max: 1000000, currency: 'INR' }, ranking: 2, established: 1961, website: 'https://www.iitd.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Hospital', 'Cafeteria', 'Gymnasium', 'Auditorium'] },
  { name: 'Indian Institute of Technology Madras', type: 'public', description: 'Leading technical institute with a beautiful campus in Chennai, known for research and innovation.', location: { address: 'IIT Madras, Adyar', city: 'Chennai', state: 'Tamil Nadu', pincode: '600036' }, fees: { min: 200000, max: 900000, currency: 'INR' }, ranking: 3, established: 1959, website: 'https://www.iitm.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Hospital', 'Cafeteria', 'Swimming Pool'] },
  { name: 'Indian Institute of Technology Kanpur', type: 'public', description: 'Renowned for its rigorous academic programs in science, engineering, and management.', location: { address: 'Kalyanpur', city: 'Kanpur', state: 'Uttar Pradesh', pincode: '208016' }, fees: { min: 200000, max: 900000, currency: 'INR' }, ranking: 4, established: 1959, website: 'https://www.iitk.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Cafeteria'] },
  { name: 'Indian Institute of Technology Kharagpur', type: 'public', description: 'The oldest and largest IIT, known for its diverse academic programs and sprawling campus.', location: { address: 'IIT Kharagpur', city: 'Kharagpur', state: 'West Bengal', pincode: '721302' }, fees: { min: 180000, max: 850000, currency: 'INR' }, ranking: 5, established: 1951, website: 'https://www.iitkgp.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Hospital', 'Cafeteria', 'Gymnasium', 'Swimming Pool'] },
  { name: 'Indian Institute of Science Bangalore', type: 'public', description: 'India\'s premier research institution for science and engineering, consistently ranked #1 for research.', location: { address: 'CV Raman Rd, Devasandra Layout', city: 'Bangalore', state: 'Karnataka', pincode: '560012' }, fees: { min: 50000, max: 500000, currency: 'INR' }, ranking: 6, established: 1909, website: 'https://www.iisc.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Research Labs', 'WiFi Campus', 'Cafeteria', 'Gymnasium', 'Auditorium'] },
  { name: 'Indian Institute of Technology Roorkee', type: 'public', description: 'One of the oldest technical institutions in Asia with a rich heritage spanning over 175 years.', location: { address: 'IIT Roorkee', city: 'Roorkee', state: 'Uttarakhand', pincode: '247667' }, fees: { min: 200000, max: 900000, currency: 'INR' }, ranking: 7, established: 1847, website: 'https://www.iitr.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Cafeteria'] },
  { name: 'Indian Institute of Technology Guwahati', type: 'public', description: 'A leading IIT known for its scenic campus on the banks of the Brahmaputra and strong research output.', location: { address: 'North Guwahati', city: 'Guwahati', state: 'Assam', pincode: '781039' }, fees: { min: 200000, max: 850000, currency: 'INR' }, ranking: 8, established: 1994, website: 'https://www.iitg.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Cafeteria'] },
  { name: 'Indian Institute of Technology Hyderabad', type: 'public', description: 'A new-generation IIT with a focus on interdisciplinary research and industry collaboration.', location: { address: 'Kandi, Sangareddy', city: 'Hyderabad', state: 'Telangana', pincode: '502285' }, fees: { min: 200000, max: 850000, currency: 'INR' }, ranking: 9, established: 2008, website: 'https://www.iith.ac.in', accreditation: 'NAAC A++ / NBA', affiliation: 'Autonomous (Institute of National Importance)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Cafeteria'] },
  { name: 'Birla Institute of Technology and Science Pilani', type: 'deemed', description: 'India\'s leading private university known for engineering, science, and management programs.', location: { address: 'Vidya Vihar', city: 'Pilani', state: 'Rajasthan', pincode: '333031' }, fees: { min: 400000, max: 2000000, currency: 'INR' }, ranking: 10, established: 1964, website: 'https://www.bits-pilani.ac.in', accreditation: 'NAAC A / NBA', affiliation: 'Deemed University (UGC)', facilities: ['Library', 'Hostel', 'Sports Complex', 'Research Labs', 'WiFi Campus', 'Cafeteria', 'Gymnasium', 'Auditorium'] },
  { name: 'National Institute of Technology Trichy', type: 'public', description: 'Top NIT in India with excellent placement records and a strong alumni network.', location: { address: 'Tiruchirappalli', city: 'Tiruchirappalli', state: 'Tamil Nadu', pincode: '620015' }, fees: { min: 125000, max: 600000, currency: 'INR' }, ranking: 11, established: 1964, website: 'https://www.nitt.edu' },
  { name: 'National Institute of Technology Surathkal', type: 'public', description: 'Premier NIT located on the beautiful coast of Karnataka, known for engineering excellence.', location: { address: 'Srinivasnagar', city: 'Mangalore', state: 'Karnataka', pincode: '575025' }, fees: { min: 125000, max: 600000, currency: 'INR' }, ranking: 12, established: 1960, website: 'https://www.nitk.ac.in' },
  { name: 'Vellore Institute of Technology', type: 'deemed', description: 'One of India\'s largest private universities with a strong focus on technology and innovation.', location: { address: 'VIT University', city: 'Vellore', state: 'Tamil Nadu', pincode: '632014' }, fees: { min: 200000, max: 1500000, currency: 'INR' }, ranking: 13, established: 1984, website: 'https://www.vit.ac.in' },
  { name: 'Delhi University', type: 'public', description: 'One of India\'s largest and most prestigious central universities offering diverse academic programs.', location: { address: 'University Enclave', city: 'New Delhi', state: 'Delhi', pincode: '110007' }, fees: { min: 10000, max: 200000, currency: 'INR' }, ranking: 14, established: 1922, website: 'https://www.du.ac.in' },
  { name: 'Jawaharlal Nehru University', type: 'public', description: 'A leading central university renowned for social sciences, humanities, and liberal arts education.', location: { address: 'New Mehrauli Road', city: 'New Delhi', state: 'Delhi', pincode: '110067' }, fees: { min: 5000, max: 100000, currency: 'INR' }, ranking: 15, established: 1969, website: 'https://www.jnu.ac.in' },
  { name: 'Indian Institute of Technology BHU Varanasi', type: 'public', description: 'A constituent institute of BHU, combining traditional values with modern technical education.', location: { address: 'BHU Campus', city: 'Varanasi', state: 'Uttar Pradesh', pincode: '221005' }, fees: { min: 200000, max: 800000, currency: 'INR' }, ranking: 16, established: 1919, website: 'https://www.iitbhu.ac.in' },
  { name: 'Anna University', type: 'public', description: 'Tamil Nadu\'s premier technical university offering engineering and technology programs.', location: { address: 'Sardar Patel Road, Guindy', city: 'Chennai', state: 'Tamil Nadu', pincode: '600025' }, fees: { min: 50000, max: 300000, currency: 'INR' }, ranking: 17, established: 1978, website: 'https://www.annauniv.edu' },
  { name: 'Jadavpur University', type: 'public', description: 'A prestigious state university in Kolkata known for engineering, arts, and science programs.', location: { address: '188, Raja S.C. Mullick Rd', city: 'Kolkata', state: 'West Bengal', pincode: '700032' }, fees: { min: 10000, max: 150000, currency: 'INR' }, ranking: 18, established: 1955, website: 'https://www.jaduniv.edu.in' },
  { name: 'SRM Institute of Science and Technology', type: 'deemed', description: 'A leading private university near Chennai with a strong engineering and medical school.', location: { address: 'SRM Nagar, Kattankulathur', city: 'Chennai', state: 'Tamil Nadu', pincode: '603203' }, fees: { min: 250000, max: 1500000, currency: 'INR' }, ranking: 19, established: 1985, website: 'https://www.srmist.edu.in' },
  { name: 'Manipal Academy of Higher Education', type: 'deemed', description: 'A top private university offering programs across engineering, medicine, and management.', location: { address: 'Tiger Circle Road', city: 'Manipal', state: 'Karnataka', pincode: '576104' }, fees: { min: 300000, max: 2500000, currency: 'INR' }, ranking: 20, established: 1953, website: 'https://www.manipal.edu' },
  { name: 'National Institute of Technology Warangal', type: 'public', description: 'One of the oldest and most reputed NITs in India with a strong technical curriculum.', location: { address: 'NIT Campus', city: 'Warangal', state: 'Telangana', pincode: '506004' }, fees: { min: 125000, max: 500000, currency: 'INR' }, ranking: 21, established: 1959, website: 'https://www.nitw.ac.in' },
  { name: 'University of Hyderabad', type: 'public', description: 'A central university known for postgraduate and research programs in sciences and humanities.', location: { address: 'Prof. C.R. Rao Road, Gachibowli', city: 'Hyderabad', state: 'Telangana', pincode: '500046' }, fees: { min: 10000, max: 200000, currency: 'INR' }, ranking: 22, established: 1974, website: 'https://www.uohyd.ac.in' },
  { name: 'Amity University Noida', type: 'private', description: 'A large private university offering 200+ programs across engineering, business, and law.', location: { address: 'Sector 125', city: 'Noida', state: 'Uttar Pradesh', pincode: '201313' }, fees: { min: 200000, max: 1500000, currency: 'INR' }, ranking: 23, established: 2005, website: 'https://www.amity.edu' },
  { name: 'Savitribai Phule Pune University', type: 'public', description: 'One of the premier universities in Maharashtra, known for research and academic excellence.', location: { address: 'Ganeshkhind Road', city: 'Pune', state: 'Maharashtra', pincode: '411007' }, fees: { min: 10000, max: 200000, currency: 'INR' }, ranking: 24, established: 1949, website: 'https://www.unipune.ac.in' },
  { name: 'Thapar Institute of Engineering and Technology', type: 'deemed', description: 'A top engineering institute in Punjab known for quality education and strong placements.', location: { address: 'Bhadson Road', city: 'Patiala', state: 'Punjab', pincode: '147004' }, fees: { min: 300000, max: 1200000, currency: 'INR' }, ranking: 25, established: 1956, website: 'https://www.thapar.edu' },
  { name: 'Indian Institute of Technology Indore', type: 'public', description: 'A new-generation IIT with cutting-edge research facilities and a growing reputation.', location: { address: 'Simrol', city: 'Indore', state: 'Madhya Pradesh', pincode: '453552' }, fees: { min: 200000, max: 800000, currency: 'INR' }, ranking: 26, established: 2009, website: 'https://www.iiti.ac.in' },
  { name: 'PSG College of Technology', type: 'autonomous', description: 'A leading autonomous engineering college in Coimbatore with excellent industry connections.', location: { address: 'Peelamedu', city: 'Coimbatore', state: 'Tamil Nadu', pincode: '641004' }, fees: { min: 100000, max: 500000, currency: 'INR' }, ranking: 27, established: 1951, website: 'https://www.psgtech.edu' },
  { name: 'Chandigarh University', type: 'private', description: 'One of India\'s fastest-growing private universities with strong placement records.', location: { address: 'NH-95, Ludhiana-Chandigarh Highway', city: 'Mohali', state: 'Punjab', pincode: '140413' }, fees: { min: 150000, max: 1200000, currency: 'INR' }, ranking: 28, established: 2012, website: 'https://www.cuchd.in' },
  { name: 'College of Engineering Pune', type: 'autonomous', description: 'One of the oldest engineering colleges in Asia, a premier autonomous institution under SPPU.', location: { address: 'Shivajinagar', city: 'Pune', state: 'Maharashtra', pincode: '411005' }, fees: { min: 100000, max: 500000, currency: 'INR' }, ranking: 29, established: 1854, website: 'https://www.coep.org.in' },
  { name: 'Banaras Hindu University', type: 'public', description: 'One of the largest residential universities in Asia with a wide range of academic programs.', location: { address: 'BHU Campus', city: 'Varanasi', state: 'Uttar Pradesh', pincode: '221005' }, fees: { min: 5000, max: 200000, currency: 'INR' }, ranking: 30, established: 1916, website: 'https://www.bhu.ac.in' },
  { name: 'National Institute of Technology Calicut', type: 'public', description: 'A leading NIT in Kerala known for engineering and technology programs.', location: { address: 'NIT Campus', city: 'Kozhikode', state: 'Kerala', pincode: '673601' }, fees: { min: 125000, max: 500000, currency: 'INR' }, ranking: 31, established: 1961, website: 'https://www.nitc.ac.in' },
  { name: 'Lovely Professional University', type: 'private', description: 'India\'s largest single-campus university offering 200+ programs across multiple disciplines.', location: { address: 'Jalandhar-Delhi G.T. Road', city: 'Phagwara', state: 'Punjab', pincode: '144411' }, fees: { min: 100000, max: 1500000, currency: 'INR' }, ranking: 32, established: 2005, website: 'https://www.lpu.in' },
  { name: 'IIIT Hyderabad', type: 'deemed', description: 'A research-focused institute specializing in computer science, AI, and related technologies.', location: { address: 'Gachibowli', city: 'Hyderabad', state: 'Telangana', pincode: '500032' }, fees: { min: 300000, max: 1000000, currency: 'INR' }, ranking: 33, established: 1998, website: 'https://www.iiit.ac.in' },
  { name: 'Christ University', type: 'deemed', description: 'A prestigious deemed university in Bangalore offering diverse programs from arts to engineering.', location: { address: 'Hosur Road', city: 'Bangalore', state: 'Karnataka', pincode: '560029' }, fees: { min: 100000, max: 800000, currency: 'INR' }, ranking: 34, established: 1969, website: 'https://www.christuniversity.in' },
  { name: 'Osmania University', type: 'public', description: 'A historic state university in Hyderabad known for its heritage campus and quality education.', location: { address: 'Amberpet', city: 'Hyderabad', state: 'Telangana', pincode: '500007' }, fees: { min: 10000, max: 150000, currency: 'INR' }, ranking: 35, established: 1918, website: 'https://www.osmania.ac.in' },
  { name: 'Jamia Millia Islamia', type: 'public', description: 'A central university in Delhi known for its inclusive education and diverse academic offerings.', location: { address: 'Jamia Nagar', city: 'New Delhi', state: 'Delhi', pincode: '110025' }, fees: { min: 5000, max: 200000, currency: 'INR' }, ranking: 36, established: 1920, website: 'https://www.jmi.ac.in' },
  { name: 'National Institute of Technology Rourkela', type: 'public', description: 'A leading NIT in Odisha with excellent research facilities and placement records.', location: { address: 'NIT Campus', city: 'Rourkela', state: 'Odisha', pincode: '769008' }, fees: { min: 125000, max: 500000, currency: 'INR' }, ranking: 37, established: 1961, website: 'https://www.nitrkl.ac.in' },
  { name: 'Aligarh Muslim University', type: 'public', description: 'A prestigious central university with a long history of academic excellence and diverse programs.', location: { address: 'AMU Campus', city: 'Aligarh', state: 'Uttar Pradesh', pincode: '202002' }, fees: { min: 5000, max: 150000, currency: 'INR' }, ranking: 38, established: 1920, website: 'https://www.amu.ac.in' },
  { name: 'KIIT University', type: 'deemed', description: 'A leading deemed university in Bhubaneswar known for engineering, law, and management programs.', location: { address: 'Patia', city: 'Bhubaneswar', state: 'Odisha', pincode: '751024' }, fees: { min: 200000, max: 1200000, currency: 'INR' }, ranking: 39, established: 1997, website: 'https://www.kiit.ac.in' },
  { name: 'Shiv Nadar University', type: 'private', description: 'A multidisciplinary research university near Delhi offering world-class education.', location: { address: 'NH-91, Tehsil Dadri', city: 'Greater Noida', state: 'Uttar Pradesh', pincode: '201314' }, fees: { min: 400000, max: 2000000, currency: 'INR' }, ranking: 40, established: 2011, website: 'https://www.snu.edu.in' },
  { name: 'Indian Institute of Technology Dhanbad', type: 'public', description: 'Formerly ISM Dhanbad, a leading IIT specializing in mining, geology, and engineering.', location: { address: 'ISM Campus', city: 'Dhanbad', state: 'Jharkhand', pincode: '826004' }, fees: { min: 200000, max: 800000, currency: 'INR' }, ranking: 41, established: 1926, website: 'https://www.iitism.ac.in' },
  { name: 'Symbiosis International University', type: 'deemed', description: 'A premier deemed university in Pune known for management, law, and liberal arts programs.', location: { address: 'Lavale, Mulshi', city: 'Pune', state: 'Maharashtra', pincode: '412115' }, fees: { min: 300000, max: 2500000, currency: 'INR' }, ranking: 42, established: 2002, website: 'https://www.siu.edu.in' },
  { name: 'Cochin University of Science and Technology', type: 'public', description: 'Kerala\'s premier technology and science university located in the port city of Kochi.', location: { address: 'South Kalamassery', city: 'Kochi', state: 'Kerala', pincode: '682022' }, fees: { min: 50000, max: 300000, currency: 'INR' }, ranking: 43, established: 1971, website: 'https://www.cusat.ac.in' },
  { name: 'Presidency University Kolkata', type: 'public', description: 'One of the oldest educational institutions in South Asia with a legacy of academic excellence.', location: { address: '86/1, College Street', city: 'Kolkata', state: 'West Bengal', pincode: '700073' }, fees: { min: 5000, max: 50000, currency: 'INR' }, ranking: 44, established: 1817, website: 'https://www.presiuniv.ac.in' },
  { name: 'National Institute of Technology Durgapur', type: 'public', description: 'A well-known NIT in West Bengal with strong industry ties and research output.', location: { address: 'Mahatma Gandhi Avenue', city: 'Durgapur', state: 'West Bengal', pincode: '713209' }, fees: { min: 125000, max: 500000, currency: 'INR' }, ranking: 45, established: 1960, website: 'https://www.nitdgp.ac.in' },
  { name: 'Visvesvaraya National Institute of Technology', type: 'public', description: 'A top NIT in Nagpur known for engineering education and research excellence.', location: { address: 'South Ambazari Road', city: 'Nagpur', state: 'Maharashtra', pincode: '440010' }, fees: { min: 125000, max: 500000, currency: 'INR' }, ranking: 46, established: 1960, website: 'https://www.vnit.ac.in' },
  { name: 'RVCE Bangalore', type: 'autonomous', description: 'One of the oldest and most reputed engineering colleges in Karnataka with industry-aligned programs.', location: { address: 'Mysore Road', city: 'Bangalore', state: 'Karnataka', pincode: '560059' }, fees: { min: 150000, max: 800000, currency: 'INR' }, ranking: 47, established: 1963, website: 'https://www.rvce.edu.in', accreditation: 'NAAC A+ / NBA', affiliation: 'Visvesvaraya Technological University', facilities: ['Library', 'Hostel', 'Sports Complex', 'WiFi Campus', 'Cafeteria', 'Gymnasium', 'Auditorium', 'Computer Labs'] },
  { name: 'Dhirubhai Ambani Institute of Information and Communication Technology', type: 'private', description: 'A specialized ICT university in Gujarat backed by Reliance, known for technology programs.', location: { address: 'Near Indroda Circle, Gandhinagar', city: 'Gandhinagar', state: 'Gujarat', pincode: '382007' }, fees: { min: 300000, max: 1200000, currency: 'INR' }, ranking: 48, established: 2001, website: 'https://www.daiict.ac.in' },
  { name: 'Indian Statistical Institute Kolkata', type: 'public', description: 'India\'s foremost institution for statistics, mathematics, and computer science.', location: { address: '203, B.T. Road', city: 'Kolkata', state: 'West Bengal', pincode: '700108' }, fees: { min: 5000, max: 100000, currency: 'INR' }, ranking: 49, established: 1931, website: 'https://www.isical.ac.in' },
  { name: 'Ashoka University', type: 'private', description: 'A leading liberal arts university near Delhi, focused on interdisciplinary and research-driven education.', location: { address: 'Plot No. 2, Rajiv Gandhi Education City', city: 'Sonipat', state: 'Haryana', pincode: '131029' }, fees: { min: 500000, max: 2000000, currency: 'INR' }, ranking: 50, established: 2014, website: 'https://www.ashoka.edu.in' },
];

const seedColleges = async () => {
  const admin = await User.findOne({ email: 'admin@campusoption.com' });

  for (const data of colleges) {
    const slug = slugify(data.name, { lower: true, strict: true });
    await College.findOneAndUpdate(
      { slug },
      { ...data, slug, status: 'published', createdBy: admin?._id || null },
      { upsert: true, setDefaultsOnInsert: true }
    );
  }

  logger.info(`Seeded ${colleges.length} colleges`);
};

module.exports = seedColleges;
